language: python
sudo: false

os:
  - osx
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5-5.7.1-beta"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libffi-dev
      - libssl-dev
      - swig

install:
  - pip install pre-commit
  - pip install -e .

script:
  - pre-commit run --all-files
  - python setup.py test
