language: python
sudo: false

services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5-5.7.1-beta"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libffi-dev
      - libssl-dev
      - swig

install:
  - pip install pre-commit
  - pip install -e .

script:
  - pre-commit run --all-files
  - python setup.py test

after_success:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]
    then
      docker build -t xenial -f docker/xenial/Dockerfile .
      mkdir deploy
      id=$(docker create xenial)
      docker cp $id:/python-fido-host-debian-packages.tar.gz deploy/python-fido-host-$TRAVIS_BRANCH-deb.tar.gz
    fi
