[tool.poetry]
name = "fido2"
version = "1.0.0-dev0"
description = ""
authors = ["Dain Nilsson <dain@yubico.com>"]

[tool.poetry.dependencies]
python = "^3.6"
cryptography = "^2.1 || ^3.0"
dataclasses = {version = "^0.8", python = "<3.7"}
uhid-freebsd = {version = "^1.2.1", platform = "FreeBSD"}
pyscard = {version = "^1.9 || ^2.0.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^6.0"
mock = "^4.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
